# Generated by Django 2.2 on 2021-10-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(null=True)),
                ('created_by', models.TextField(blank=True, verbose_name='created_by')),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_by', models.TextField(blank=True, verbose_name='Last_modified_by')),
                ('version_number', models.IntegerField(null=True)),
                ('identifier', models.TextField(blank=True, verbose_name='Identifier')),
                ('year', models.IntegerField(null=True, verbose_name='Year')),
                ('place', models.TextField(blank=True, verbose_name='Place')),
                ('volume', models.TextField(blank=True, verbose_name='Volume')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='api_tests.Work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
