# Generated by Django 2.2 on 2021-10-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0002_edition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='user',
        ),
    ]
