# Generated by Django 2.2 on 2021-10-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_tests', '0003_auto_20211028_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(null=True)),
                ('created_by', models.TextField(blank=True, verbose_name='created_by')),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_by', models.TextField(blank=True, verbose_name='Last_modified_by')),
                ('version_number', models.IntegerField(null=True)),
                ('accept', models.BooleanField(null=True)),
                ('summary_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('public', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decider', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='api_tests.Work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
