# Generated by Django 2.2 on 2021-10-29 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_tests', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='genre',
            field=models.TextField(blank=True, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PublicationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(null=True)),
                ('created_by', models.TextField(blank=True, verbose_name='created_by')),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_by', models.TextField(blank=True, verbose_name='Last_modified_by')),
                ('version_number', models.IntegerField(null=True)),
                ('current_stage', models.TextField(blank=True, null=True, verbose_name='Stage')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
