# Generated by Django 2.2 on 2021-10-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0006_auto_20211029_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='api_tests.Project'),
        ),
    ]
