# Generated by Django 2.2 on 2021-10-29 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_tests', '0007_auto_20211029_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
