# Generated by Django 2.2 on 2021-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0011_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationplan',
            name='editors',
            field=models.ManyToManyField(blank=True, to='api_tests.Editor'),
        ),
    ]
